/* tslint:disable */
/* eslint-disable */
/**
 * NAPMap Stations API
 * NAPMap - Alternative fuel stations registry API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: maros.bednar@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface Station
 */
export interface Station {
    /**
     * Unique station identifier
     * @type {string}
     * @memberof Station
     */
    'id': string;
    /**
     * Station name
     * @type {string}
     * @memberof Station
     */
    'name': string;
    /**
     * Type of station
     * @type {string}
     * @memberof Station
     */
    'stationType': StationStationTypeEnum;
    /**
     * Supported fuel types
     * @type {Array<string>}
     * @memberof Station
     */
    'fuels': Array<StationFuelsEnum>;
    /**
     * Operator company name
     * @type {string}
     * @memberof Station
     */
    'operatorName': string;
    /**
     * Street address
     * @type {string}
     * @memberof Station
     */
    'address': string;
    /**
     * City name
     * @type {string}
     * @memberof Station
     */
    'city': string;
    /**
     * Country code
     * @type {string}
     * @memberof Station
     */
    'country'?: string;
    /**
     * GPS latitude
     * @type {number}
     * @memberof Station
     */
    'lat': number;
    /**
     * GPS longitude
     * @type {number}
     * @memberof Station
     */
    'lng': number;
    /**
     * Operating hours
     * @type {string}
     * @memberof Station
     */
    'openingHours'?: string;
    /**
     * Maximum charging power in kW
     * @type {number}
     * @memberof Station
     */
    'maxPowerKw'?: number;
    /**
     * Available connector types
     * @type {Array<string>}
     * @memberof Station
     */
    'connectors'?: Array<string>;
    /**
     * Additional services
     * @type {Array<string>}
     * @memberof Station
     */
    'services'?: Array<string>;
    /**
     * Station status
     * @type {string}
     * @memberof Station
     */
    'status'?: StationStatusEnum;
}

export const StationStationTypeEnum = {
    Charging: 'CHARGING',
    Refueling: 'REFUELING'
} as const;

export type StationStationTypeEnum = typeof StationStationTypeEnum[keyof typeof StationStationTypeEnum];
export const StationFuelsEnum = {
    Electric: 'ELECTRIC',
    Hydrogen: 'HYDROGEN',
    Cng: 'CNG',
    Lng: 'LNG',
    Lpg: 'LPG'
} as const;

export type StationFuelsEnum = typeof StationFuelsEnum[keyof typeof StationFuelsEnum];
export const StationStatusEnum = {
    Active: 'ACTIVE',
    Inactive: 'INACTIVE'
} as const;

export type StationStatusEnum = typeof StationStatusEnum[keyof typeof StationStatusEnum];


/**
 * StationsApi - axios parameter creator
 * @export
 */
export const StationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Register a new fuel station
         * @summary Create new station
         * @param {Station} station Station to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createStation: async (station: Station, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'station' is not null or undefined
            assertParamExists('createStation', 'station', station)
            const localVarPath = `/stations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(station, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Soft delete - sets status to INACTIVE
         * @summary Delete station
         * @param {string} stationId Station ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteStation: async (stationId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'stationId' is not null or undefined
            assertParamExists('deleteStation', 'stationId', stationId)
            const localVarPath = `/stations/{stationId}`
                .replace(`{${"stationId"}}`, encodeURIComponent(String(stationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns details of a specific station
         * @summary Get station details
         * @param {string} stationId Station ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStation: async (stationId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'stationId' is not null or undefined
            assertParamExists('getStation', 'stationId', stationId)
            const localVarPath = `/stations/{stationId}`
                .replace(`{${"stationId"}}`, encodeURIComponent(String(stationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns list of fuel stations with optional filtering
         * @summary Get list of stations
         * @param {string} [city] Filter by city name
         * @param {GetStationsFuelEnum} [fuel] Filter by fuel type
         * @param {GetStationsStationTypeEnum} [stationType] Filter by station type
         * @param {string} [operator] Filter by operator name
         * @param {GetStationsStatusEnum} [status] Filter by status (default ACTIVE)
         * @param {number} [minPowerKw] Minimum power in kW
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStations: async (city?: string, fuel?: GetStationsFuelEnum, stationType?: GetStationsStationTypeEnum, operator?: string, status?: GetStationsStatusEnum, minPowerKw?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/stations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (city !== undefined) {
                localVarQueryParameter['city'] = city;
            }

            if (fuel !== undefined) {
                localVarQueryParameter['fuel'] = fuel;
            }

            if (stationType !== undefined) {
                localVarQueryParameter['stationType'] = stationType;
            }

            if (operator !== undefined) {
                localVarQueryParameter['operator'] = operator;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (minPowerKw !== undefined) {
                localVarQueryParameter['minPowerKw'] = minPowerKw;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update an existing station
         * @summary Update station
         * @param {string} stationId Station ID
         * @param {Station} station Updated station data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateStation: async (stationId: string, station: Station, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'stationId' is not null or undefined
            assertParamExists('updateStation', 'stationId', stationId)
            // verify required parameter 'station' is not null or undefined
            assertParamExists('updateStation', 'station', station)
            const localVarPath = `/stations/{stationId}`
                .replace(`{${"stationId"}}`, encodeURIComponent(String(stationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(station, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * StationsApi - functional programming interface
 * @export
 */
export const StationsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = StationsApiAxiosParamCreator(configuration)
    return {
        /**
         * Register a new fuel station
         * @summary Create new station
         * @param {Station} station Station to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createStation(station: Station, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Station>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createStation(station, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StationsApi.createStation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Soft delete - sets status to INACTIVE
         * @summary Delete station
         * @param {string} stationId Station ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteStation(stationId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteStation(stationId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StationsApi.deleteStation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns details of a specific station
         * @summary Get station details
         * @param {string} stationId Station ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStation(stationId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Station>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStation(stationId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StationsApi.getStation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns list of fuel stations with optional filtering
         * @summary Get list of stations
         * @param {string} [city] Filter by city name
         * @param {GetStationsFuelEnum} [fuel] Filter by fuel type
         * @param {GetStationsStationTypeEnum} [stationType] Filter by station type
         * @param {string} [operator] Filter by operator name
         * @param {GetStationsStatusEnum} [status] Filter by status (default ACTIVE)
         * @param {number} [minPowerKw] Minimum power in kW
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStations(city?: string, fuel?: GetStationsFuelEnum, stationType?: GetStationsStationTypeEnum, operator?: string, status?: GetStationsStatusEnum, minPowerKw?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Station>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStations(city, fuel, stationType, operator, status, minPowerKw, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StationsApi.getStations']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update an existing station
         * @summary Update station
         * @param {string} stationId Station ID
         * @param {Station} station Updated station data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateStation(stationId: string, station: Station, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Station>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateStation(stationId, station, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StationsApi.updateStation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * StationsApi - factory interface
 * @export
 */
export const StationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = StationsApiFp(configuration)
    return {
        /**
         * Register a new fuel station
         * @summary Create new station
         * @param {Station} station Station to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createStation(station: Station, options?: any): AxiosPromise<Station> {
            return localVarFp.createStation(station, options).then((request) => request(axios, basePath));
        },
        /**
         * Soft delete - sets status to INACTIVE
         * @summary Delete station
         * @param {string} stationId Station ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteStation(stationId: string, options?: any): AxiosPromise<void> {
            return localVarFp.deleteStation(stationId, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns details of a specific station
         * @summary Get station details
         * @param {string} stationId Station ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStation(stationId: string, options?: any): AxiosPromise<Station> {
            return localVarFp.getStation(stationId, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns list of fuel stations with optional filtering
         * @summary Get list of stations
         * @param {string} [city] Filter by city name
         * @param {GetStationsFuelEnum} [fuel] Filter by fuel type
         * @param {GetStationsStationTypeEnum} [stationType] Filter by station type
         * @param {string} [operator] Filter by operator name
         * @param {GetStationsStatusEnum} [status] Filter by status (default ACTIVE)
         * @param {number} [minPowerKw] Minimum power in kW
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStations(city?: string, fuel?: GetStationsFuelEnum, stationType?: GetStationsStationTypeEnum, operator?: string, status?: GetStationsStatusEnum, minPowerKw?: number, options?: any): AxiosPromise<Array<Station>> {
            return localVarFp.getStations(city, fuel, stationType, operator, status, minPowerKw, options).then((request) => request(axios, basePath));
        },
        /**
         * Update an existing station
         * @summary Update station
         * @param {string} stationId Station ID
         * @param {Station} station Updated station data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateStation(stationId: string, station: Station, options?: any): AxiosPromise<Station> {
            return localVarFp.updateStation(stationId, station, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * StationsApi - object-oriented interface
 * @export
 * @class StationsApi
 * @extends {BaseAPI}
 */
export class StationsApi extends BaseAPI {
    /**
     * Register a new fuel station
     * @summary Create new station
     * @param {Station} station Station to create
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StationsApi
     */
    public createStation(station: Station, options?: RawAxiosRequestConfig) {
        return StationsApiFp(this.configuration).createStation(station, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Soft delete - sets status to INACTIVE
     * @summary Delete station
     * @param {string} stationId Station ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StationsApi
     */
    public deleteStation(stationId: string, options?: RawAxiosRequestConfig) {
        return StationsApiFp(this.configuration).deleteStation(stationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns details of a specific station
     * @summary Get station details
     * @param {string} stationId Station ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StationsApi
     */
    public getStation(stationId: string, options?: RawAxiosRequestConfig) {
        return StationsApiFp(this.configuration).getStation(stationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns list of fuel stations with optional filtering
     * @summary Get list of stations
     * @param {string} [city] Filter by city name
     * @param {GetStationsFuelEnum} [fuel] Filter by fuel type
     * @param {GetStationsStationTypeEnum} [stationType] Filter by station type
     * @param {string} [operator] Filter by operator name
     * @param {GetStationsStatusEnum} [status] Filter by status (default ACTIVE)
     * @param {number} [minPowerKw] Minimum power in kW
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StationsApi
     */
    public getStations(city?: string, fuel?: GetStationsFuelEnum, stationType?: GetStationsStationTypeEnum, operator?: string, status?: GetStationsStatusEnum, minPowerKw?: number, options?: RawAxiosRequestConfig) {
        return StationsApiFp(this.configuration).getStations(city, fuel, stationType, operator, status, minPowerKw, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update an existing station
     * @summary Update station
     * @param {string} stationId Station ID
     * @param {Station} station Updated station data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StationsApi
     */
    public updateStation(stationId: string, station: Station, options?: RawAxiosRequestConfig) {
        return StationsApiFp(this.configuration).updateStation(stationId, station, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const GetStationsFuelEnum = {
    Electric: 'ELECTRIC',
    Hydrogen: 'HYDROGEN',
    Cng: 'CNG',
    Lng: 'LNG',
    Lpg: 'LPG'
} as const;
export type GetStationsFuelEnum = typeof GetStationsFuelEnum[keyof typeof GetStationsFuelEnum];
/**
 * @export
 */
export const GetStationsStationTypeEnum = {
    Charging: 'CHARGING',
    Refueling: 'REFUELING'
} as const;
export type GetStationsStationTypeEnum = typeof GetStationsStationTypeEnum[keyof typeof GetStationsStationTypeEnum];
/**
 * @export
 */
export const GetStationsStatusEnum = {
    Active: 'ACTIVE',
    Inactive: 'INACTIVE'
} as const;
export type GetStationsStatusEnum = typeof GetStationsStatusEnum[keyof typeof GetStationsStatusEnum];


